# Generated by Django 2.1.7 on 2019-03-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guy',
            fields=[
                ('name', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'guy',
            },
        ),
    ]
