# Generated by Django 2.1.7 on 2019-03-13 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_auto_20190312_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='streaming_service',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='studio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.Metadata'),
        ),
        migrations.AlterField(
            model_name='tvepisode',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.Metadata'),
        ),
        migrations.AlterField(
            model_name='tvepisode',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.Metadata'),
        ),
    ]
