# Generated by Django 2.1.7 on 2019-03-18 05:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_auto_20190312_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_watched', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='file_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tvepisode',
            name='file_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='watchevent',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.Movie'),
        ),
        migrations.AddField(
            model_name='watchevent',
            name='part_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.WatchHistory'),
        ),
        migrations.AddField(
            model_name='watchevent',
            name='tv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.TVEpisode'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='watch_history',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.WatchHistory'),
        ),
    ]
