# Generated by Django 2.1.7 on 2019-03-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_auto_20190317_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tvepisode',
            name='thumbnail_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='thumbnail_path',
            field=models.TextField(default=''),
        ),
    ]
