# Generated by Django 2.1.7 on 2019-03-23 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_auto_20190318_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_siteuser_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
