# Generated by Django 2.1.7 on 2019-04-09 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0008_auto_20190326_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='friends',
        ),
        migrations.AddField(
            model_name='friend',
            name='follows',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='friends',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.Friend'),
        ),
    ]
