# Generated by Django 2.1.7 on 2019-04-14 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_siteuser_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('statement', models.CharField(default='charge', max_length=50)),
                ('charged_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='billing',
            name='num_rentals',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='num_sub_slots',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='transaction_info',
        ),
        migrations.AddField(
            model_name='billing',
            name='unsub_list',
            field=models.ManyToManyField(blank=True, to='streaming.TVShow'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='part_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.Billing'),
        ),
    ]
