# Generated by Django 2.1.7 on 2019-04-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_siteuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='bio',
            field=models.CharField(default='', max_length=500),
        ),
    ]
