# Generated by Django 2.1.7 on 2019-04-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0011_auto_20190414_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='bio',
            field=models.CharField(default='', max_length=500),
        ),
    ]
