# Generated by Django 2.1.7 on 2019-04-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0015_auto_20190419_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='rentals',
            field=models.ManyToManyField(blank=True, through='streaming.Rental', to='streaming.Movie'),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, through='streaming.Subscription', to='streaming.TVShow'),
        ),
    ]
