# Generated by Django 2.1.7 on 2019-04-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0018_auto_20190424_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='cvc_num',
            field=models.CharField(default='', max_length=3),
        ),
    ]
